### PR TITLE
Select wrapped text

### LINKED ISSUE #27: selection should not take sub-lines from soft wrapping
Hi this is a very nice extension, but I noticed that when soft wrapping is activated, the column selection will select sub lines.
I would appreciate if it would not or if there was a toggle to have both mode.

Thanks

### LINKED ISSUE #79: soft wrap
My column selection is not working when soft wrap is on. It also do not work well when screen is spitted in two half with ctrl+k left.

### PR DESCRIPTION
**Pull request by evmorov**
fixes #79 and fixes #27

Demo:
soft-wrap-fix

At the beginning I show that nothing is broken. Then I copy wrapped text and paste it. Then I modify the wrapped text.

### CODE REVIEW

**Comment by evmorov** [comment]
I've added a commit that fixes #40.
I didn't want to make them in one pull request but there would be a conflict if I added it to another branch.

**Comment by evmorov** [comment]
Also it fixes #90

**Comment by RyanZim** [comment]
@bigfive ping? I would really like to see #27 fixed.

**Comment by bigfive** [comment]
Great work. Thank you so much!

**Pull request merged**
