### PR TITLE
Change cursor style on crosshair while selecting

### PR DESCRIPTION
**Pull request by sadovnychyi**
sample

#12

Ready to discuss ideas about improvements.
We, probably, should trigger style change on _middleMouseDown event as well? Ideas?

It's a bit annoying that you have to move a cursor a bit after a key down to apply new style. Any ideas how to fix this?

### CODE REVIEW

**Comment by kolomiichenko** [comment]
:+1:

**Comment by bigfive** [comment]
Nice

**Comment by sadovnychyi** [comment]
It's a bit late.. Should I fix conflicts?

**Comment by sadovnychyi** [comment]
Fixed

**Comment by bigfive** [comment]
You're a star. Thanks

**Comment by bigfive** [comment]
Merged prematurely I'm afraid, had to revert. It looks like you removed middle mouse functionality

**Comment by sadovnychyi** [comment]
Is it related to this lines? I've removed them because this method is not used anywhere. Am I wrong?

```
_keyDown = (e) ->
  e[inputCfg.selectKey]
```

**Comment by bigfive** [comment]
Reopened here https://github.com/bigfive/atom-sublime-select/pull/84

**Pull request merged**
