### PR TITLE
Change activationEvents to activationCommands

### PR DESCRIPTION
**Pull request by Ingramz**
Fixes a deprecation warning

### CODE REVIEW

**Comment by yuzhigang33** [comment]
+1

**Comment by mc10** [comment]
@bigfive It'd be great if this got merged in, as v1.0.0 will completely remove deprecated features. This PR fixes #42, #46, #47, #48, #51, and #52, and closes #43, so those issues/PRs should be closed when this gets merged in.

**Comment by mc10** [comment]
@Ingramz Technically `activationCommands` should be `{}` as commands should be grouped by selector, but since it's empty I don't think it will make too big of a difference.

**Comment by Ingramz** [comment]
@mc10 you are right, technically it should be `{}`. However empty array does the job as well. The best solution however would be removing that line as it would default to correct value anyway.

Also technically any of these pull requests that me or someone else has posted do not need to be merged because when the deprecations are removed, this plainly does nothing.

**Comment by jtokoph** [comment]
I've published an update that removes activationEvents from the package.json file.

**Pull request closed without merging**
