### PR TITLE
Remove deprecated `displayBuffer` references

### LINKED ISSUE #126: Deprecated calls
Atom 1.13.0 beta 5 has deprecated TextEditor.prototype.displayBuffer.

sublime-style-column-selection (1 deprecation)
TextEditor.prototype.displayBuffer has always been private, but now it is gone. Reading the displayBuffer property now returns a reference to the containing TextEditor, which now provides some of the API of the defunct DisplayBuffer class.
TextEditor.get - /Applications/Atom Beta.app/Contents/Resources/app.asar/src/text-editor.js:101:14
SublimeSelectEditorHandler._setup_vars - /Users/dfreed/.atom/packages/Sublime-Style-Column-Selection/lib/editor-handler.coffee:100:40
new SublimeSelectEditorHandler - /Users/dfreed/.atom/packages/Sublime-Style-Column-Selection/lib/editor-handler.coffee:17:12
module.exports.switch_editor_handler - /Users/dfreed/.atom/packages/Sublime-Style-Column-Selection/lib/sublime-select.coffee:136:34
Function.module.exports.Emitter.simpleDispatch - /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:25:14
Emitter.emit - /Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:129:28

### PR DESCRIPTION
**Pull request by Greenek**
Fixes #126

### CODE REVIEW

**Comment by verysmallriver** [comment]
Can someone merge this PR?

**Review by brayfe — APPROVED** [review]
Tested this with latest version of atom today and it worked.  No deprecation warning and was still able to edit multiple lines.

**Comment by dc-avasilev** [comment]
thanks man!!!

**Comment by djui** [comment]
Please someone merge this PR. The deprecation warnings are not nice.

**Comment by jpwalters** [comment]
Bump ... Lots of open issues would be fixed by this one pull request.

**Comment by WaKeMaTTa** [comment]
@bigfive Can you merge this commit please. Thanks.

**Comment by bigfive** [comment]
Tested. Works well. Thanks all for the patience 😬

**Comment by mjbrender** [comment]
Thanks for maintaining this feature @bigfive!

**Comment by naoliden** [comment]
Can anyone tell me how does the fix work? What do I do to fix it?

**Pull request merged**
