### PR TITLE
Fixed Issue #42: Changed key activationEvents

### PR DESCRIPTION
**Pull request by h3rnan**
Changed key "activationEvents"

### CODE REVIEW

**Comment by h3rnan** [comment]
Ups!!

**Comment by ksmithut** [comment]
@bigfive ping

any word on getting this merged in?

**Comment by jasonrudolph** [comment]
I tried this out and it indeed resolves the deprecation warning. :+1: 

@bigfive: It would be awesome to get this merged.

I :heart: this package. Thanks for making it available. :bow:

**Comment by doughsay** [comment]
@bigfive please merge! Thanks!

**Comment by goddamnhippie** [comment]
:+1:

**Comment by jtokoph** [comment]
I've published an update that removes activationEvents from the package.json file.

**Pull request closed without merging**
